---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: details
  name: details
  namespace: default
spec:
  clusterIP: 10.3.237.213
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: details
  sessionAffinity: None
  type: ClusterIP
