---
apiVersion: v1
kind: Service
metadata:
  name: flux
  namespace: default
spec:
  clusterIP: 10.3.81.7
  ports:
  - nodePort: 32547
    port: 80
    protocol: TCP
    targetPort: 3030
  selector:
    name: flux
  sessionAffinity: None
  type: LoadBalancer
