---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  clusterIP: 10.3.154.239
  ports:
  - name: grafana
    nodePort: 32587
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
