---
apiVersion: v1
kind: Service
metadata:
  labels:
    istio: pilot
  name: istio-pilot
  namespace: default
spec:
  clusterIP: 10.3.138.99
  ports:
  - name: http-discovery
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-apiserver
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    istio: pilot
  sessionAffinity: None
  type: ClusterIP
