---
apiVersion: v1
kind: Service
metadata:
  name: istio-egress
  namespace: default
spec:
  clusterIP: 10.3.136.154
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    istio: egress
  sessionAffinity: None
  type: ClusterIP
