---
apiVersion: v1
kind: Service
metadata:
  labels:
    istio: ingress
  name: istio-ingress
  namespace: default
spec:
  clusterIP: 10.3.55.212
  ports:
  - name: http
    nodePort: 31809
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30926
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    istio: ingress
  sessionAffinity: None
  type: LoadBalancer
