---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: productpage
  name: productpage
  namespace: default
spec:
  clusterIP: 10.3.37.217
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: productpage
  sessionAffinity: None
  type: ClusterIP
