---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    name: prometheus
  name: prometheus
  namespace: default
spec:
  clusterIP: 10.3.190.169
  ports:
  - name: prometheus
    nodePort: 32126
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: LoadBalancer
