---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reviews
  name: reviews
  namespace: default
spec:
  clusterIP: 10.3.117.157
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: reviews
  sessionAffinity: None
  type: ClusterIP
