---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: default
spec:
  clusterIP: 10.3.166.63
  ports:
  - name: http
    nodePort: 32493
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: zipkin
  sessionAffinity: None
  type: LoadBalancer
