---
apiVersion: v1
kind: Service
metadata:
  labels:
    operated-alertmanager: "true"
  name: alertmanager-operated
  namespace: tectonic-system
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: mesh
    port: 6783
    protocol: TCP
    targetPort: 6783
  selector:
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
