---
apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
    k8s-app: alertmanager
  name: alertmanager-main
  namespace: tectonic-system
spec:
  clusterIP: 10.3.149.184
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    alertmanager: main
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
