---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: container-linux-update-operator
    managed-by-channel-operator: "true"
  name: container-linux-update-operator
  namespace: tectonic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: container-linux-update-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: container-linux-update-operator
      name: container-linux-update-operator
    spec:
      containers:
      - command:
        - /bin/update-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/coreos/container-linux-update-operator:v0.2.1
        imagePullPolicy: IfNotPresent
        name: update-operator
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
