---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-state-metrics
  name: kube-state-metrics
  namespace: tectonic-system
spec:
  clusterIP: 10.3.116.130
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    k8s-app: kube-state-metrics
  sessionAffinity: None
  type: ClusterIP
