---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kube-version-operator
    managed-by-channel-operator: "true"
  name: kube-version-operator
  namespace: tectonic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-version-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: kube-version-operator
        tectonic-app-version-name: kubernetes
    spec:
      containers:
      - command:
        - /kube-version-operator
        - --cache-images=true
        - --version-mapping=/upgrade-spec.json
        image: quay.io/coreos/kube-version-operator:v1.6.7
        imagePullPolicy: IfNotPresent
        name: kube-version-operator
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: coreos-pull-secret
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      terminationGracePeriodSeconds: 30
