---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: prometheus
    name: prometheus
    prometheus: k8s
  name: prometheus
  namespace: tectonic-system
spec:
  clusterIP: 10.3.65.150
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: None
  type: ClusterIP
