---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: tectonic-prometheus-operator
    managed-by-channel-operator: "true"
  name: tectonic-prometheus-operator
  namespace: tectonic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tectonic-prometheus-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: tectonic-prometheus-operator
        tectonic-app-version-name: tectonic-monitoring
    spec:
      containers:
      - args:
        - -logtostderr=true
        - -v=4
        image: quay.io/coreos/tectonic-prometheus-operator:v1.3.0
        imagePullPolicy: IfNotPresent
        name: tectonic-prometheus-operator
        resources:
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: coreos-pull-secret
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      terminationGracePeriodSeconds: 30
