---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: ingress-controller
    k8s-app: tectonic-lb
  name: tectonic-lb
  namespace: tectonic-system
spec:
  clusterIP: 10.3.33.73
  ports:
  - name: https
    nodePort: 32000
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    nodePort: 32001
    port: 80
    protocol: TCP
    targetPort: 80
  - name: health
    nodePort: 32002
    port: 10254
    protocol: TCP
    targetPort: 10254
  selector:
    component: ingress-controller
    k8s-app: tectonic-lb
  sessionAffinity: None
  type: NodePort
