---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: tectonic-monitoring-auth-alertmanager
  name: tectonic-monitoring-auth-alertmanager
  namespace: tectonic-system
spec:
  clusterIP: 10.3.179.125
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: http
  selector:
    k8s-app: tectonic-monitoring-auth-alertmanager
  sessionAffinity: None
  type: ClusterIP
