---
apiVersion: v1
kind: Service
metadata:
  name: tectonic-identity-api
  namespace: tectonic-system
spec:
  clusterIP: 10.3.86.90
  ports:
  - name: api
    port: 5557
    protocol: TCP
    targetPort: 5557
  selector:
    component: identity
    k8s-app: tectonic-identity
  sessionAffinity: None
  type: ClusterIP
