---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: ui
    k8s-app: tectonic-console
  name: tectonic-console
  namespace: tectonic-system
spec:
  clusterIP: 10.3.130.32
  ports:
  - name: tectonic-console
    nodePort: 32739
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    component: ui
    k8s-app: tectonic-console
  sessionAffinity: None
  type: NodePort
