---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: tectonic-channel-operator
    managed-by-channel-operator: "true"
  name: tectonic-channel-operator
  namespace: tectonic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tectonic-channel-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: tectonic-channel-operator
        tectonic-app-version-name: tectonic-cluster
    spec:
      containers:
      - env:
        - name: CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: clusterID
              name: tectonic-config
        image: quay.io/coreos/tectonic-channel-operator:0.3.6
        imagePullPolicy: IfNotPresent
        name: tectonic-channel-operator
        resources:
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: certs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: coreos-pull-secret
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/ca-certificates
        name: certs
